#!/usr/bin/env bash

function _kong_profile {
  local shome="${_kong_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/vendor/kong/bin:$PATH"
}

_kong_profile
