#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  export LD_LIBRARY_PATH="${BOARD_PATH}/install/lib"
  local ver_kong="$(kong version 2>/dev/null || true)"
  jq -n --arg kong "$ver_kong" '{kong: $kong}'
}

version "$@"
