#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_kong="0.0.1"
  jq -n --arg kong "$ver_kong" '{kong: $kong}'
}

version "$@"
